In [1]:
import numpy as np

## Linear Algebra

In [2]:
A = np.arange(9).reshape((3,3))

In [3]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
B = np.arange(6).reshape((3,2))

In [5]:
B

array([[0, 1],
       [2, 3],
       [4, 5]])

In [6]:
A.dot(B)         # Dot Product

array([[10, 13],
       [28, 40],
       [46, 67]])

In [7]:
A @ B            # Cross Product

array([[10, 13],
       [28, 40],
       [46, 67]])

In [8]:
B.T              # Transposing Matrix (Row -> Column)

array([[0, 2, 4],
       [1, 3, 5]])

In [9]:
B.T @ A

array([[30, 36, 42],
       [39, 48, 57]])

In [49]:
a = np.ones((2,3))
b = np.full((3,2), 2)

np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

##### 

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Useful Numpy Function

> ### **_random_** 

In [10]:
np.random.random(size=2)

array([0.87703883, 0.00441454])

In [11]:
np.random.normal(size=2)

array([1.70735009, 0.67703229])

In [12]:
a = np.random.rand(2,4)

a

array([[0.30050935, 0.5391203 , 0.74931024, 0.02109562],
       [0.64836858, 0.11858777, 0.97090987, 0.49650493]])

In [13]:
np.random.random_sample(a.shape)

array([[0.02407814, 0.35260774, 0.91520684, 0.40605541],
       [0.58268672, 0.22485919, 0.41212259, 0.69301581]])

In [14]:
np.random.randint(10, size=(3,3))

array([[5, 1, 8],
       [4, 2, 7],
       [2, 0, 9]])

----------------------------------------------------------------------------------------------------------------------

> ### **_arange_** 

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [17]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

-------------------------------------------------------------------------------------------------------------

> ### vtsack

In [5]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

----------------------------------------------------------------------------------------------------------------------

> ### hstack

In [6]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

----------------------------------------------------------------------------------------------------------------------

> ### **_reshape_** 

In [18]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

----------------------------------------------------------------------------------------------------

> ### **_linspace_** 

In [20]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [22]:
np.linspace(0, 1, 2, False)

array([0. , 0.5])

------------

> ### **_zeros, ones, empty_** 

In [23]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [24]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [26]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [27]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [29]:
np.empty((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

----------------------------------------------------------------------------------------------------------------------

> ### **_identity and eye_** 

In [30]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.eye(8,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

-----------------------------------------------

> ### ***full***

In [35]:
a = np.full((2,2), 5)

a

array([[5, 5],
       [5, 5]])

In [36]:
b = np.full((2,2,2), 7)

b

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [37]:
np.full((2,2,3), [7,10,1])

array([[[ 7, 10,  1],
        [ 7, 10,  1]],

       [[ 7, 10,  1],
        [ 7, 10,  1]]])

-- -----------------------------

> ### ***full_like***

In [38]:
np.full_like(a, 4)

array([[4, 4],
       [4, 4]])

In [39]:
np.full_like(b, 8)

array([[[8, 8],
        [8, 8]],

       [[8, 8],
        [8, 8]]])

----------------------------------------------------------------------------------------------------------------------

> ### ***repeat***

In [40]:
arr = np.array([[1,2,3]])
r = np.repeat(arr, 3, axis=0)

r

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

----------------------------------------------------------------------------------------------------------------------

> ### ***copy***

In [44]:
a = np.array([1,2,3,4])
b = a
b[0] = 10
a

array([10,  2,  3,  4])

In [46]:
a = np.array([1,2,3,4])
b = a.copy()
b[0] = 10
a

array([1, 2, 3, 4])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Logic Functions

> #### any()

In [41]:
# Returns True if ANY element in array is zero.

a = np.array([1,2,3,4,5,6,0])
a.any()

True

> #### all()

In [42]:
# Returns True if there is NO zero. All none zero.

a = np.array([1,2,3,4,5,6])
a.all()

True

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

##### 

## Mathematics

***Check Out For List of Math Func.*** ->  https://numpy.org/doc/stable/reference/routines.math.html

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

##### 

## Miscellaneous

> ### Load Data From File

In [10]:
file = np.genfromtxt('data/untitled.txt', delimiter=',')

file

array([[ 23.,  43.,   6.,   4.,   3.,   2., 532.,  34.,   6.,  23.,  23.,
         12.],
       [ 65.,  76.,   7.,  54.,  34.,  21., 123.,  35.,   7.,   8.,  63.,
         23.],
       [987.,   8., 754.,  43.,  32.,  21.,  23.,  65.,   7.,  98.,   9.,
         90.]])

In [11]:
file = file.astype('int32')

In [15]:
file[file >50]                 # Works just like pandas

array([532,  65,  76,  54, 123,  63, 987, 754,  65,  98,  90])

In [19]:
file[(file>50) & (file<100)]

array([65., 76., 54., 63., 65., 98., 90.])