In [2]:
import numpy as np

> ### Vectorized Operations

In [3]:
a = np.arange(4)

In [4]:
a

array([0, 1, 2, 3])

In [5]:
a + 10

array([10, 11, 12, 13])

In [6]:
a*10

array([ 0, 10, 20, 30])

In [7]:
a                  # Original not altered yet

array([0, 1, 2, 3])

In [8]:
a += 100

a                  # Now assignment operator override the array

array([100, 101, 102, 103])

In [9]:
b = np.array([10,10,10,10])

In [10]:
a+b                # Arrays need to be of same shape

array([110, 111, 112, 113])

In [11]:
a*b

array([1000, 1010, 1020, 1030])

##### 

> ### Boolean Arrays

(Also called masks)

remember: axis=0 columns; axis=1 rows

In [12]:
a = np.arange(4)

In [13]:
a

array([0, 1, 2, 3])

In [15]:
a[[0,-1]]              # Selecting first and last using Multi-indexing

array([0, 3])

In [20]:
a[[True, False, False, True]]        # Selecting first and last using Boolean

array([0, 3])

In [22]:
a >= 2                    # Getting boolean array with elements as True if they are equal or greater than 2

array([False, False,  True,  True])

In [23]:
a[a >= 2]                 # Now we used this condition of masking to get the array having TRUE values

array([2, 3])

In [24]:
a.mean()

1.5

In [25]:
a[a > a.mean()]           # Showing array having True value for mean greater than 1.5 

array([2, 3])

In [26]:
a[~(a > a.mean())]

array([0, 1])

In [27]:
a[ (a==0) | (a==1) ]

array([0, 1])

In [30]:
a[ (a<=2) & (a%2==0) ]

array([0, 2])

##### 

In [32]:
A = np.random.randint(100, size=(3,3))

A

array([[17, 47, 26],
       [38, 72,  5],
       [42, 74, 91]])

In [36]:
A = np.random.randint(100,110, size=(3,3))

A

array([[102, 101, 104],
       [109, 109, 102],
       [106, 103, 100]])

In [37]:
A[np.array([
    [True, False, False],
    [False, True, True],
    [True,False, True]
])]

array([102, 109, 102, 106, 100])

In [38]:
A > 105

array([[False, False, False],
       [ True,  True, False],
       [ True, False, False]])

In [39]:
A[A > 105]

array([109, 109, 106])